**1. Write a Python Program to Add Two Matrices?**  
ANS - 

In [10]:
import numpy as np 

m1 = np.arange(8).reshape(2,4)
m2 = np.random.randint(1,15,8).reshape(2,4)

print(m1, "\n") 
print(m2, "\n")

print(np.add(m1,m2))


[[0 1 2 3]
 [4 5 6 7]] 

[[ 4  4  3  1]
 [ 8 12  5 11]] 

[[ 4  5  5  4]
 [12 17 11 18]]


**2. Write a Python Program to Multiply Two Matrices?**  
ANS - 

In [17]:
m1 = np.random.randint(1,10,8).reshape(2,2,2)
m2 = np.random.randint(1,12,8).reshape(2,2,2)

product = np.dot(m1,m2)

print("The product of array {} \n\n and array {} \n\n is \n\n {} ".format(m1,m2,product))

The product of array [[[3 8]
  [2 2]]

 [[2 1]
  [6 2]]] 

 and array [[[ 2  6]
  [ 9 10]]

 [[ 2  8]
  [ 5  6]]] 

 is 

 [[[[78 98]
   [46 72]]

  [[22 32]
   [14 28]]]


 [[[13 22]
   [ 9 22]]

  [[30 56]
   [22 60]]]] 


**3. Write a Python Program to Transpose a Matrix?**  
ANS - 

In [21]:
X = [[1,2],
     [3,4],
     [5,6]]

result = [[0,0,0],
          [0,0,0]]
          

for i in range(len(X)): 
  for j in range(len(X[0])):
    result[j][i] = X[i][j] 

for r in result:
  print(r)   

[1, 3, 5]
[2, 4, 6]


**4. Write a Python Program to Sort Words in Alphabetic Order?**  
ANS - 

In [25]:
#Taking input of string

str = input("Enter a string : ")

words = str.split()

words.sort()

print(" \n The sorted words are \n ")
for word in words:
  print(word)

Enter a string : Hello bye Take care Good night
 
 The sorted words are 
 
Good
Hello
Take
bye
care
night


**5. Write a Python Program to Remove Punctuation From a String?**  
ANS - 

In [28]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

s = input("Enter a string : ")
no_punct = ""
for ch in s :
  if ch not in  punctuations :
    no_punct += ch 

print(no_punct)

Enter a string : Hello.... welcome...!! How are you?
Hello welcome How are you
